# Generated by Django 4.0.2 on 2022-02-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date_in_hours', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('asa_id', models.IntegerField()),
                ('asa_name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('option_1_address', models.CharField(default='', max_length=100)),
                ('option_2_address', models.CharField(default='', max_length=100)),
                ('question', models.TextField(max_length=300)),
                ('option_one', models.CharField(max_length=100)),
                ('option_two', models.CharField(max_length=100)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TotalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UpcommingPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('upcomming_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='IsActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_pool', models.IntegerField(default=39135000)),
                ('Active_polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed_polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcomming', to='polls.poll')),
            ],
        ),
    ]
