import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import algoSS from "../assets/myAlgo.png";
import algo from "../assets/algoSH.png";
import algoSigner from "../assets/algoSigner.png";
import im from "../assets/add.png";
import download from "../assets/download.jpg";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex bg-black h-20 items-center justify-center">
        <h1 className="text-3xl  text-white">Welcome to XavyWays</h1>
      </div>
      <div className="w-full flex justify-center">
        <p>
          You need an algorand wallet to continue.
          <br />
          <b>Get started now!</b>
        </p>
      </div>
      <div className="w-full flex justify-center mt-20">
        <div className="cursor-pointer w-40v h-2/5 bg-white grid grid-cols-2 h-40v ">
          <div className="w-20v flex flex-wrap justify-center items-center h-20v border-2 border-sky-500">
            <Link href="/generate">
              <Image src={im} width={40} height={40} alt="Algo Picture" />
            </Link>
            <p className="flex text-center">Generate a new Algorand wallet</p>
          </div>
          <div className="w-20v h-20v border-2 border-sky-500 flex flex-wrap justify-center items-center">
            <Link href="/import">
              <Image src={download} width={50} height={50} alt="Algo Picture" />
            </Link>
            <p className="flex text-center">Import an existing account</p>
          </div>
          <div className="w-20v h-20v border-2 border-sky-500 flex flex-wrap justify-center items-center">
            <Link href="/algosigner">
              <Image
                src={algoSigner}
                width={60}
                height={60}
                alt="Algo Picture"
              />
            </Link>
            <p className="flex text-center">
              Simply create or import yout Algosigner account
            </p>
          </div>
          <div className=" justify-center items-centerw-20v h-20v border-2 border-sky-500 flex flex-wrap">
            <Link href="/walletConnect">
              <Image src={algo} width={65} height={60} alt="Algo Picture" />
            </Link>

            <p className="flex text-center">WalletConnect</p>
          </div>
          <div className=" justify-center items-centerw-20v h-20v border-2 border-sky-500 flex flex-wrap">
            <Link href="/myalgo">
              <Image src={algoSS} width={65} height={60} alt="Algo Picture" />
            </Link>

            <p className="flex text-center">
              Securely sign transactions with nmy Algo Connect
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
