import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css"
import { useEffect, useState } from "react";
import Link from "next/link";
import { useGlobalContext } from "../components/context";
import Header from "../components/header";
export default function Home() {
  const { propsObj, setPropsObj } = useGlobalContext();

  useEffect(() => {
    let storage = localStorage.getItem("proposals");
    if (!storage) {
      localStorage.setItem("proposals", JSON.stringify(Obj));
      storage = localStorage.getItem("proposals");
    }
    console.log("Change")
    setPropsObj(JSON.parse(storage));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>New Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <h1 className={styles.title}>
          Welcome to <Link href="/new/proposals">Choice Proposals</Link>
        </h1>

        <p className={styles.description}>
          Get started by making a Proposal{" "}
          <code className={styles.code}><Link href={"/new/proposals"}>Here</Link></code>
        </p>

        <div className={styles.grid}>
          {propsObj &&
            propsObj.map(({ name, desc, id }, key) => {
              return (
                <details className={styles.card} key={key}>
                  <summary className="overflow-hidden">
                    <div className="">{name}</div>
                    {"  "}#{id}
                    <Link href={`/${id}`}>&rarr;</Link>
                  </summary>
                  <Link href={`/${id}`}>
                    <a className="cursor-pointer overflow-auto flex ">
                      {desc.slice(0, 150)}...
                    </a>
                  </Link>
                </details>
              );
            })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const Obj = [
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
    id: "1",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Placeat rem saepe libero. Nostrum numquam enim non. Consequuntur, quos odit iusto, temporibus aliquam quisquam enim ea numquam fugiat veniam dolorum commodi",
    id: "2",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
    id: "3",
  },
];
