import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useGlobalContext } from "../components/context";
import Header from "../components/header";
import { useRouter } from "next/router";
import {AiOutlineEdit} from "react-icons/ai"

export default function Home() {

  const { propsObj, setPropsObj } = useGlobalContext();
  const router = useRouter();

  useEffect(() => {
    let storage = window.localStorage.getItem("proposals");
    if (!storage) {
      localStorage.setItem("proposals", JSON.stringify(Obj));
      storage = localStorage.getItem("proposals");
    }
    console.log("Change");
    setPropsObj(JSON.parse(storage));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>New Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={` ${styles.main}`}>
        <h1 className={`mt-8 ${styles.title}`}>
          Welcome to <Link href="/new/proposals">Choice Proposals</Link>
        </h1>
        <h2
          className={`text-lg text-center font-mono mt-2 max-w-md ${styles.descriptio}`}
        >
          A new and Intuitive way of making Proposals for the Choice Coin DAO
        </h2>
        <p className={styles.description}>
          Get started by making a Proposal{" "}
          <div
            className={`${styles.cod} animate-bounce rounded mt-6 text-white bg-blue-500 border-2 hover:text-blue-500 hover:bg-white hover:border-blue-500`}
          >
            <Link href={"/new/proposals"}>
              <a className="block ">Here</a>
            </Link>
          </div>
        </p>
      </main>
      <section className={`m-0 p-0 bg-blue-400 pt-6`}>
          <div className="text-3xl text-white my-3 text-center">PROPOSALS</div>
        <div className={`bg-blue-400 m-0 p-0 ${styles.grid}`}>
          {propsObj &&
            propsObj?.map(({ name, desc, id }, key) => {
              return (
                <details
                  className={`${styles.card} hover:translate-x-3 transition-transform delay-200 ease-in-out shadow-lg`}
                  key={key}
                >
                  <summary className="overflow-hidden">
                    <div className="">{name}</div>
                    {"  "}#{id}
                    <div className="flex justify-evenly w-28  ml-auto">
                      <div
                        className=" w-screen"
                        onClick={() => {
                          router.push(`/edit/${id}`);
                        }}
                      >
                        <AiOutlineEdit className="inline cursor-pointer" />
                      </div>
                    </div>
                  </summary>
                  <Link href={`/${id}`}>
                    <a className="cursor-pointer overflow-auto flex ">
                      {desc?.slice(0, 150)}...
                    </a>
                  </Link>
                </details>
              );
            })}
        </div>
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const Obj = [
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
    id: "1",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Placeat rem saepe libero. Nostrum numquam enim non. Consequuntur, quos odit iusto, temporibus aliquam quisquam enim ea numquam fugiat veniam dolorum commodi",
    id: "2",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
    id: "3",
  },
];
