# Generated by Django 4.0.2 on 2022-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('discord_id', models.CharField(default='', max_length=200)),
                ('github_url', models.CharField(default='', max_length=200)),
                ('twitter_handle', models.CharField(default='', max_length=200)),
                ('wallet_address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
