# Generated by Django 4.0.2 on 2022-02-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss_bash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', models.CharField(max_length=200)),
                ('reward', models.IntegerField()),
            ],
        ),
    ]
