"""empty message

Revision ID: 167f7ffb9119
Revises:
Create Date: 2021-12-08 06:11:11.431761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "167f7ffb9119"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=58), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "elections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("choice_per_vote", sa.Integer(), nullable=False),
        sa.Column("process_image", sa.LargeBinary(), nullable=True),
        sa.Column("is_working", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_started", sa.Boolean(), nullable=True),
        sa.Column("is_finished", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_elections_slug"), "elections", ["slug"], unique=True)
    op.create_table(
        "candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("image", sa.LargeBinary(), nullable=True),
        sa.Column("address", sa.String(length=58), nullable=False),
        sa.Column("private_key", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["election_id"],
            ["elections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("private_key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidates")
    op.drop_index(op.f("ix_elections_slug"), table_name="elections")
    op.drop_table("elections")
    op.drop_table("wallets")
    # ### end Alembic commands ###
