# Generated by Django 4.0.2 on 2022-02-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='github_url',
            new_name='NIN',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='discord_id',
            new_name='voter_ID',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='twitter_handle',
            new_name='ward',
        ),
    ]
