# Generated by Django 4.0.2 on 2022-02-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contestant',
            name='ward',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
