# Generated by Django 4.0.2 on 2022-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_contestant_state_contestant_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='full_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
