# Generated by Django 4.0.2 on 2022-02-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_contestant_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('full_name', models.CharField(default='', max_length=40)),
                ('state', models.CharField(default='', max_length=20)),
                ('ward', models.CharField(default='', max_length=100)),
                ('office', models.CharField(choices=[('Governor', 'Governor'), ('Senator', 'Senator'), ('House of Reprentatives', 'House of Representatives'), ('House of Assembly', 'House of Assembly'), ('Local Government Chairman', 'Local Government Chairman'), ('Councelor', 'Councelor')], max_length=100)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Presidential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('full_name', models.CharField(default='', max_length=40)),
                ('state', models.CharField(default='', max_length=20)),
                ('office', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
    ]
