# Generated by Django 4.0.2 on 2022-02-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_otheroffice_presidential_delete_contestant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
