export const homeObjone = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Governance",
  headLine: "Decentralized voting",
  description:
    "The Choice Coin Network is prioritizing democracy, and will incentivize its participants to help it fundamentally change how decisions are made on a large scale.",
  buttonLabel: "Cast your vote",
  imgStart: false,
  img: require("../../images/svg3.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
};
export const homeObjtwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Hold and Earn",
  headLine: "Participatory Validation",
  description:
    "Holders of Choice Coin can immediately vote on allocations for the network, which will help democratic causes and organizations.",
  buttonLabel: "Buy Now",
  imgStart: true,
  img: require("../../images/svg2.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: false,
};
export const homeObjthree = {
  id: "services",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Programmers",
  headLine: "Open Development",
  description:
    "The Choice Coin Network is entirely open source, and all participants can develop openly on both Choice Coin and its voting protocol.",
  buttonLabel: "Join Us",
  imgStart: false,
  img: require("../../images/svg4.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
};
export const homeObjfour = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "A Growing Community",
  headLine: "Choice coin to the WORLD!!",
  description:
    "The Choice Coin community is rapidly expanding thanks to our engagement and incentive programs. As this open-source project continues to grow, we look forward to building the new age of decentralized governance. Learn more about Choice Coin by checking out our Github Repos, participation incentives, official blog, and documentation below.",
  buttonLabel: "Learn Now",
  imgStart: true,
  img: require("../../images/svg5.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: false,
};
