import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useEffect, useState } from "react";
import { useGlobalContext } from "../../components/context";
import Header from "../../components/header";
import Proposal from "../../components/pages/proposal";
import NotConnected from "../../components/pages/notConnected";
export default function Proposals() {
  const { propsObj, setPropsObj,isConnected } = useGlobalContext();

  useEffect(() => {
    let storage = localStorage.getItem("proposals");
    if (storage) {
      localStorage.setItem("proposals", JSON.stringify(Obj));
      storage = localStorage.getItem("proposals");
    }
    setPropsObj(JSON.parse(storage));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}  flex justify-evenly`}>
          <div className="text-3xl mb-4 uppercase">New Proposals</div>
        <Header />
        {isConnected?<><Proposal/></>:<><NotConnected/></>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const Obj = [
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
    id: "1",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Placeat rem saepe libero. Nostrum numquam enim non. Consequuntur, quos odit iusto, temporibus aliquam quisquam enim ea numquam fugiat veniam dolorum commodi",
    id: "2",
  },
  {
    name: "prince",
    desc: "Welcome to the wild wild west",
    id: "3",
  },
];
