import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "../components/footer";
import Rewards from "../components/RewardsComponent.tsx"
import { useEffect, useState } from "react";
import Link from "next/link";
import { useGlobalContext } from "../components/context";
import Header from "../components/header";
import { useRouter } from "next/router";
import defaultRewardArray from "../components/defaultRewardArray";

export default function Home() {
  const { propsObj, setPropsObj, setAddress, address } = useGlobalContext();
  const router = useRouter();

  useEffect(() => {
    let storage = localStorage.getItem("rewardsList");
    if (!storage) {
      localStorage.setItem("rewardsList", JSON.stringify(defaultRewardArray));
      storage = localStorage.getItem("rewardsList");
    }
    setPropsObj(JSON.parse(storage));
  }, []);
  // const handleDelete = (param) => {
  //   const filteredArray = propsObj?.filter((_, index) => {
  //     return index !== param;
  //   });
  //   const answer = confirm("Are you sure you want to delete this Proposal?");
  //   if (answer) {
  //     setPropsObj(filteredArray);
  //     localStorage.setItem("proposals", JSON.stringify(filteredArray));
  //     alert("Proposal Deleted Successfully");
  //   }
  // };

  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={` ${styles.main} space-y-6`}>
        <h1 className={`mt-8 text-4xl text-center`}>
          Welcome to Choice Rewards 
        </h1>
        <h2
          className={`text-lg text-center font-mono mt-2 max-w-md ${styles.descriptio}`}
        >
          A way to reward Outstanding members of the DAO
        </h2>
        <p className={styles.description}>
          Fill in info
          <Link href={"/new/reward"} >
            <a
              className={`${styles.code} block rounded mt text-gray-900 bg-gray-100 border-2 hover:text-blue-500 hover:bg-white hover:border-blue-500`}
            >
              Here
            </a>
          </Link>
        </p>
      </main>
      <Rewards/>
      <Footer />
    </div>
  );
}
